### ISSUE TITLE
Issues with next page button

### ISSUE THREAD

**Issue by FloatingAl** [fribbels/Fribbels-Epic-7-Optimizer#46] opened 2021-03-05 01:09 UTC
When optimizing gear, the filter is not showing the arrow button for the set of permutations. 
I believe it could be from my end but I just wanted to make sure.
UI is showing a "?" when showing the listed amount of combinations.

![image](https://user-images.githubusercontent.com/15023251/110052373-82674500-7d25-11eb-9bad-d620ab0eaa32.png)

**Comment by fribbels** [comment] 2021-03-05 03:05
It used to show it when I was using a previous version of the Ag Grid library, but when I upgraded to the latest the button disappears. There's not much I can do from my side - I believe this is a bug from Ag Grid. Fortunately though there's not many cases where people need to look at multiple 500+ result pages

**Comment by fribbels** [comment] 2021-03-05 12:43
Looks like the issue is tracked here, but is fixed in their documentation https://github.com/ag-grid/ag-grid/issues/4295 - I'll check if there's an update to fix it

**Comment by cam-m** [comment] 2021-03-22 00:38
> Looks like the issue is tracked here, but is fixed in their documentation [ag-grid/ag-grid#4295](https://github.com/ag-grid/ag-grid/issues/4295) - I'll check if there's an update to fix it

FYI its still not fixed in 25.1.0 and can be reproduced in their doco - [opened a new issue](https://github.com/ag-grid/ag-grid/issues/4411) (since they won't review comments on closed issues)...

**Comment by fribbels** [comment] 2021-03-24 08:51
The main thing I wanted to fix was the page navigation feature which is now working again:

![https://i.imgur.com/66a3Z1O.png](https://i.imgur.com/66a3Z1O.png)

But yeah question mark weirdness is still there but doesn't affect us too much. Thanks for opening up the issue with them though

**Comment by FloatingAl** [comment] 2021-03-25 23:13
Yeah its not a big issue. If anything I can see what I can do on my end or you can probably find a different  library similar to Ad grid.

**Closed** 2021-06-03 10:34 UTC
Labels: bug
